<?php


/**
 * Implements hook_menu().
 */
function multistepform_menu() {

  $items = array();
  $items['admin/config/content/webform/multistepform'] = array(
     'title' => 'Multiple step form with webforms',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('multistepform_config'),
     'access arguments' => array('access content'),
     'file' => 'multistepform.admin.inc',
     'type' => MENU_NORMAL_ITEM,
  );
  $items['survey'] = array(
    'title' => 'Customer Survey',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('multistepform_survey_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['complete-page'] = array(
    'title' => 'Survey Complete',
    'page callback' => 'customer_survey_complete',
    'page arguments' => array(),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

function multistepform_survey_form($form, &$form_state) {
  if (!isset($form_state['stage'])) $form_state['stage'] = 0;
     $steps = variable_get('multistepform_steps', array());
     $count = count($steps);
  if ($count && ($form_state['stage'] < $count)) {
    $nid = $steps[$form_state['stage']];
    $node = node_load($nid);
    $node->webform['redirect_url'] = '<none>';
     if (isset($form_state['storage']) && isset($form_state['storage']['component_tree'])) unset($form_state['storage']['component_tree']);
     if (isset($form_state['storage']) && isset($form_state['storage']['submitted'])) unset($form_state['storage']['submitted']);
     if (isset($form_state['values']) && isset($form_state['values']['submitted']))  unset($form_state['values']['submitted']);
    if (isset($form_state['form_submission'][$nid]) && isset($form_state['form_submission'][$nid]['sid'])) {
      module_load_include('inc','webform','webform.submissions');
      $submissions = webform_get_submission($nid, $form_state['form_submission'][$nid]['sid']);
      return webform_client_form($form, $form_state, $node, $submissions);
    } else {
     return webform_client_form($form, $form_state, $node);
    }
  }else {
    $form['completion'] = array('#markup' => variable_get('multistepform_completion_message',
t('Thank you submission')),);
  }
  return $form;
}
function multistepform_survey_form_validate($form, &$form_state) {

}
function multistepform_survey_form_submit($form, &$form_state) {
  $form_state['rebuild'] = TRUE;
  
  if ($form_state['values']['op'] == 'Back') {
     $form_state['stage'] = $form_state['stage'] - 1;
  } else {
     if (!isset($form_state['form_submission'])) $form_state['form_submission'] = array();
      $steps = variable_get('multistepform_steps', array());
      $form_state['form_submission'][$steps[$form_state['stage']]]['sid'] = $form_state['values']['details']['sid'];
      unset($form_state['values']['details']);
      $form_state['stage'] = $form_state['stage'] + 1;
     
  }

}
function multistepform_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'multistepform_survey_form':
      $form['#submit'][] = 'multistepform_survey_form_submit';
      $form['#validate'][] = 'multistepform_survey_form_validate';
      $steps = variable_get('multistepform_steps', array());
      $count = count($steps);
      if (isset($form_state['stage']) && $form_state['stage'] > 0 && $form_state['stage'] < $count) {
        $form['back'] = array(
          '#type' => 'submit',
          '#value' => 'Back',
        );
      }
      if (isset($form_state['stage']) && ($form_state['stage'] != ($count - 1))) {
        $form['actions']['submit']['#value'] = 'Next';
      }
  }
}
