<?php
function autism_custom_init() {
  if (drupal_is_front_page()) {
    drupal_add_js(array('autism_custom' => array('supporter_count' => number_format(variable_get('autism_custom_supporter_count', 0)))), 'setting');
    drupal_add_js('jQuery(document).ready(function () {  jQuery("span.numbers").html( Drupal.settings.autism_custom.supporter_count); });', 'inline');
 }
}

function autism_custom_views_post_execute(&$view) { 	 
 if($view->name == "stream" && $view->current_display == 'stream_topic_page' && $view->query->pager->current_page === 0) {
	 $nidarg = arg(1);  
	 if ($nidarg > 0) {
    	 $node = node_load($nidarg);
         $data = new stdclass(); 
         $items = $view->result[0];
         foreach($items as $key => $item) {
			 if ($key == 'nid') {
                $data->nid = $node->nid;
	         } elseif ($key == 'node_created') {
                $data->node_created = $node->created;
             } else {
			   $data->{$key} = is_array($item) ? array() : '';	 
			 }
	     }
         array_unshift($view->result, $data);
    } 
 }  
    
}


function getcommentcount_past2week($nid) {
  if (!is_numeric($nid)){
    return false;
  }
  $time = time();
  $from = $time - (variable_get('autism_custom_past_week', 0) * 604800);
  
  // Create an object of type SelectQuery
  $query = db_select('comment', 'c');
   
  // Add extra detail to this query object: a condition, fields and a range
  $query->condition('c.created', array($from, $time), 'between');
  $query->condition('c.nid', $nid);
  $query->condition('status', '1');
  return $query->countQuery()->execute()->fetchField();
}


function autism_custom_menu() {
    $items = array();    
    $items['admin/content/website'] = array(
        'title' => 'Settings Form',
	'page callback' => 'drupal_get_form',
        'page arguments' => array('autism_custom_settings_form'),
	'access arguments' => array('access_settings_form_website'),
        'type' => MENU_LOCAL_TASK, //Will appear in Navigation menu.
      );
    return $items;
}

function autism_custom_settings_form($form, &$form_state) {
  $form['autism_custom_supporter_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of members and supporters'),
    '#default_value' => variable_get('autism_custom_supporter_count', 0),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('The Number of members and supporters for the community.'),
    '#required' => TRUE,
  );
   $form['autism_custom_comment_count'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of comments to check in past week'),
    '#default_value' => variable_get('autism_custom_comment_count', 0),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Number of comments to check in past week'),
    '#required' => TRUE,
  );
  $form['autism_custom_past_week'] = array(
    '#type' => 'textfield',
    '#title' => t('Past Weeks'),
    '#default_value' => variable_get('autism_custom_past_week', 0),
    '#size' => 10,
    '#maxlength' => 2,
    '#description' => t('The week since the members and the supporters.'),
    '#required' => TRUE,
  );
 
  return system_settings_form($form);
}

function autism_custom_settings_form_validate($form, &$form_state){
  $max_num = $form_state['values']['autism_custom_supporter_count'];
  if (!is_numeric($max_num)){
    form_set_error('autism_custom_supporter_count', t('You must enter a number for the number of members and supporters in community.'));
  }
  elseif ($max_num <= 0){
    form_set_error('autism_custom_supporter_count', t('Number of members and supporters of community to display must be positive.'));
  }
  $max_week = $form_state['values']['autism_custom_past_week'];
  if (!is_numeric($max_week)){
    form_set_error('autism_custom_past_week', t('You must enter a number for the number of weeks.'));
  }
  elseif (($max_week <= 0)||($max_week>52)){
    form_set_error('autism_custom_past_week', t('Number of weeks exceeded for the year or enter a value apart from zero.'));
  }
  $max_num = $form_state['values']['autism_custom_comment_count'];
  if (!is_numeric($max_num)){
    form_set_error('autism_custom_comment_count', t('You must enter a number for the number of comments.'));
  }
  elseif ($max_num <= 0){
    form_set_error('autism_custom_comment_count', t('Number of comments to display must be positive.'));
  }
}

function autism_custom_permission() {
  return array(
    'access_settings_form_website' => array(
      'title' => t('Access settings form for the website'),
    )
  );
}

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query 
 */
function autism_custom_views_query_alter(&$view, &$query) {
  
  if ($view->name == 'stream' && $view->current_display == 'stream_topic_page' && isset($query->table_queue['field_data_eq_node']) && isset($query->table_queue['eq_node_node'])) {
    if(is_numeric(arg(1)) && arg(0) == 'node'){
    $node = node_load(arg(1));
      if (isset($node->field_stream_order_reference['und'][0]['target_id'])) {
       $name = db_select('entityqueue_subqueue', 'eq')
                ->fields('eq',array('name', 'queue'))
                ->condition('subqueue_id',$node->field_stream_order_reference['und'][0]['target_id'])
                ->execute()
                ->fetchAll();
       $queue = array_shift($name);
       $query->table_queue['field_data_eq_node']['join']->extra[0]['field'] = 'bundle';
       $query->table_queue['field_data_eq_node']['join']->extra[0]['value'] = $queue->queue;
       $query->table_queue['field_data_eq_node']['join']->definition['extra'][0]['field'] = 'bundle';
       $query->table_queue['field_data_eq_node']['join']->definition['extra'][0]['value'] = $queue->queue;       
       $query->table_queue['eq_node_node']['join']->extra[0]['field'] = 'name';                
       $query->table_queue['eq_node_node']['join']->extra[0]['value'][0] = $queue->name;
       

       $query->table_queue['eq_node_node']['join']->definition['extra'][0]['field'] = 'name';                
       $query->table_queue['eq_node_node']['join']->definition['extra'][0]['value'][0] = $queue->name;
     }
    }
  }
  if ($view->name == 'stream' && $view->current_display == 'stream_forum_page') {
    $query->add_field('node', 'nid', 'node_nid', array('function' => 'groupby'));
    $query->add_groupby('node.nid');
    $query->distinct = TRUE;
    $join = new views_join();
    $join->table = 'comment';
    $join->field = 'nid';
    $join->left_table = 'node';
    $join->left_field = 'nid';
    $join->type = 'left';
    $join->extra = 'past_comment.created <= UNIX_TIMESTAMP() -(86400*14)';
    $query->add_relationship('past_comment', $join, 'node');
    dpm($query);
  }
}
