<?php

function autism_custom_views_post_execute(&$view) { 
	 
 if($view->name == "stream" && $view->current_display == 'block_1') {
	 $nidarg = arg(1);
	 if ($nidarg > 0) {
    	 $node = node_load($nidarg);
         $data = new stdclass(); 
         $items = $view->result[0];
         foreach($items as $key => $item) {
			 if ($key == 'nid') {
                $data->nid = $node->nid;
	         } elseif ($key == 'node_created') {
                $data->node_created = $node->created;
             } else {
			   $data->{$key} = is_array($item) ? array() : '';	 
			 }
	     }
         array_unshift($view->result, $data);
    } 
 } 
    
}
