<?php
function header_form_menu() {
  // A menu callback is required when using ajax outside of the Form API.
  $items['header/form/%/%'] = array(
    'page callback' => 'ajax_next_form_response',
    'page arguments' => array(2,3),
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function header_form_block_info() {
  $blocks['are_you_with_us'] = array(
    'info' => t('Are you with us? header form'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function header_form_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'are_you_with_us':
      $block['subject'] = t('Are you with us?');
      $block['content'] = get_header_form(0);
      break;
  }
  return $block;
}

function get_header_form($pageno) {
  switch ($pageno) {
        case 0:
          $block = module_invoke('webform', 'block_view', 'client-block-74666');
          $output = render($block['content']);
          $_SESSION['first_name'] = "";
        break;
        case 1:
          $output = '<div id="slider-container" class="slider-container">';
          $plink = l('<span class="icon-Leftarrow"></span>', 'header/form/ajax/0', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));          
          $output .= '<div class="l-s-arrow">'.$plink.'</div>';
          $output .= '<div class="username element-invisible">'.$_SESSION['first_name'].'</div>';
          $block = module_invoke('webform', 'block_view', 'client-block-74671');
          $output .= render($block['content']);
          $nlink = l('<span class="icon-Rightarrow"></span>', 'header/form/ajax/2', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));
          $output .= '<div class="r-s-arrow">'.$nlink.'<p class="skip"><a class="use-ajax" href="/header/form/ajax/2">Skip</a></p></div>';
          $output .= '</div>';
        break;
        case 2:
          $output = '<div id="slider-container" class="slider-container">';
          $plink = l('<span class="icon-Leftarrow"></span>', 'header/form/ajax/1', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));          
          $output .= '<div class="l-s-arrow">'.$plink.'</div>';
          $block = module_invoke('webform', 'block_view','client-block-74676');
          $output .= render($block['content']);
          $nlink = l('<span class="icon-Rightarrow"></span>', 'header/form/ajax/3', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));	
          $output .= '<div class="r-s-arrow">'.$nlink.'<p class="skip"><a class="use-ajax" href="/header/form/ajax/3">Skip</a></p></div>';
          $output .= '</div>' ;      
        break;
        case 3:
          $output = '<div id="slider-container" class="slider-container">';
          $plink = l('<span class="icon-Leftarrow"></span>', 'header/form/ajax/2', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));          
          $output .= '<div class="l-s-arrow">'.$plink.'</div>';
          $block = module_invoke('webform', 'block_view', 'client-block-74681');
          $output .= render($block['content']);
          $output .= '</div>';
        break;
        case 4:
          $output = '<div id="slider-container" class="slider-container">';
          $plink = l('<span class="icon-Leftarrow"></span>', 'header/form/ajax/0', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));          
          $output .= '<div class="l-s-arrow">'.$plink.'</div>';
          $block = module_invoke('webform', 'block_view', 'client-block-74971');
          $output .= render($block['content']);
          $output .= '</div>';
          break;
    }
    return $output;
}

function ajax_next_form_response($type, $pageno) {
   drupal_add_library('system', 'drupal.ajax');
   if ($type == 'ajax') {
    $output = get_header_form($pageno);     
    $commands = array();
    // See ajax_example_advanced.inc for more details on the available commands
    // and how to use them.
    $commands[] = ajax_command_replace('#slider-container', $output);
    $page = array('#type' => 'ajax', '#commands' => $commands);
    ajax_deliver($page);
   } else {
    $output = t("This is some content delivered via a page load.");
    return $output;
  }
}

function header_form_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'webform_client_form_74666':
    array_unshift($form['#submit'], 'are_you_with_us_submit' );
    $form['#prefix'] = '<div id="slider-container" class="slider-container">';
    $link = l('<span class="icon-Rightarrow"></span>', 'header/form/ajax/1', array('attributes' => array('class' => array('use-ajax')),'html' => TRUE));
      $form['#suffix'] = '<div class="r-s-arrow">'.$link.'</div></div>';
      $form['submitted']['yes-i-am'] = array(
        '#type' => 'submit',
        '#value' => 'Yes I am',
        '#submit' => $form['#submit'],
        '#validate' => array('yes_i_am_validate'),
        '#ajax' =>  array(
        'callback' => 'webform_ajax_callback',
          'wrapper' => 'slider-container',
          'progress' => array(
            'message' => '',
            'type' => 'throbber',
          ),
        ),
        '#id' => drupal_html_id('edit-webform-ajax-yes-i-am-' .$form['#node']->nid)
      );
      /*$form['submitted']['not_right_now'] = array(
        '#type' => 'submit',
        '#value' => 'Not right now',
        '#submit' => $form['#submit'],
        '#ajax' =>  array(
          'callback' => 'webform_ajax_callback',
          'wrapper' => 'slider-container',
          'progress' => array(
            'message' => '',
            'type' => 'throbber',
          ),
        ),
        '#id' => drupal_html_id('edit-webform-ajax-not-right-now-' .$form['#node']->nid)
      );*/
      $form['submitted']['not_right_now'] = array(
	  '#type' => 'markup',
	  '#markup' => '<a href="#" class="btn" id="not_right_now">Not right now</a>',
	);
    break;
    case 'search_block_form':
      $form['#attributes']['class'][] = 'search-form';
      $form['search_block_form']['#attributes']['placeholder'] = 'Start typing to search the site';
    break;
    default:  
  }
}

function are_you_with_us_submit($form, &$form_state) {
  $form_state['values']['submitted']['button_clicked'] = $form_state['values']['op'];
  $form_state['values']['op'] = $form['actions']['submit']['#value'];
  $_SESSION['first_name'] = $form_state['values']['submitted']['first_name'];
}
function yes_i_am_validate($form, &$form_state) {
  if (empty($form_state['values']['submitted']['first_name'])) {
    form_set_error('submitted][first_name', 'Fill field first name');
  }
  if (empty($form_state['values']['submitted']['email'])) {
    form_set_error('submitted][email', 'Fill field email');
  } elseif (!valid_email_address($form_state['values']['submitted']['email'])) {
    form_set_error('submitted][email', 'Enter valid email');
  }
}
