<?php

function swear_words_menu() { 
    $items = array();  
    $items['admin/content/swear_words'] = array(
      'title' => 'Email swear notification',
      'description' => 'Email swear notification notification for user.',
      'page callback' => 'drupal_get_form', 
      'page arguments' => array('swear_email_settings_form'),
      'access arguments' => array('config_settings_swear_word'), 
      'type' => MENU_LOCAL_TASK, 
    );
  return $items;
}

function swear_words_permission() {
  return array(
    'config_settings_swear_word' => array(
      'title' => t('Access swear words notify settings form'),
    ) 
  );
}

function swear_email_settings_form($form, &$form_state) { 
  $form['swear_notification'] = array(
    '#type' => 'radios', 
    '#title' => t('Email notification'), 
    '#default_value' => variable_get('swear_notification', 0), 
    '#options' => array(t('Disable'), t('Enable')), 
  );     
  $form['swear_notify_email'] = array(
    '#type' => 'textarea', 
    '#title' => t('User email'), 
    '#default_value' => variable_get('swear_notify_email',''), 
    '#description' => t('Seperate email addresses by using ","'),
  );  
  $form['swear_email_subject'] = array(
    '#type' => 'textfield', 
    '#title' => t('Email subject'), 
    '#default_value' => variable_get('swear_email_subject',''),  
  );  
   $form['swear_email_body'] = array(
    '#type' => 'textarea', 
    '#title' => t('Email message'), 
    '#default_value' => variable_get('swear_email_body',''),  
  );  
  $form['swear_words'] = array(
    '#type' => 'textarea', 
    '#title' => t('Swear words list'), 
    '#default_value' => variable_get('swear_words',''),  
    '#description' => 'Seperate Swear words by using ","',
  ); 
  $form['submit'] = array('#type' => 'submit', '#value' => t('Save configuration'));
  return $form; 
}

function swear_email_settings_form_validate($form, &$form_state) { 
  $valid_email = valid_email_address($form_state['values']['swear_notify_email']);  
  if($form_state['values']['swear_notification'] == 1) { 
    if(empty($form_state['values']['swear_notify_email']) || $valid_email != 1 ){ 
      form_set_error('swear_notify_email', t('Email id is not valid, correct the email.')); 
    } 
    if(empty($form_state['values']['swear_email_subject'])){ 
      form_set_error('swear_email_subject', t('Subject field value is required')); 
    }
    if(empty($form_state['values']['swear_words'])){ 
      form_set_error('swear_words', t('Swear words field value is required')); 
    }
     if(empty($form_state['values']['swear_email_body'])){ 
      form_set_error('swear_words', t('Message field value is required')); 
    }
  }  
}  
function swear_email_settings_form_submit($form, &$form_state) {   
  variable_set('swear_notification', $form_state['values']['swear_notification']);
  variable_set('swear_notify_email', $form_state['values']['swear_notify_email']); 
  variable_set('swear_email_subject', $form_state['values']['swear_email_subject']);
  variable_set('swear_email_body', $form_state['values']['swear_email_body']); 
  variable_set('swear_words', $form_state['values']['swear_words']);  
  drupal_set_message('The configuration options have been saved.');
} 
function swear_words_comment_insert($comment) {
  search_swear_words($comment);
}
function swear_words_comment_update($comment) {
  search_swear_words($comment);
}

function search_swear_words($comment) {
  if(variable_get('swear_notification', 0) == 1){
    switch($comment->node_type) {
      case 'comment_node_forum_discussion':
      case 'comment_node_article':
      case 'comment_node_my_voice_blog':
      $swear_word = array();
      $module = 'swear_email';
      $key = 'swear';
      $to = variable_get('swear_notify_email','');
      $to = explode( ',', $to);
      $language = language_default();
      
      $node = node_load($comment->nid); 
      $comment_count = $node->comment_count + 1;
      $page = comment_new_page_count($comment_count, 1, $node);
      $comment_url = rtrim(url('node/' . $comment->nid, array('query' => $page, 'absolute'=> TRUE, 'fragment' => 'comment-' . $comment->cid)));    
      $no_swear_words = false; 
    
      $list = explode("," ,variable_get('swear_words','')); 
      $comment_body = strip_tags($comment->comment_body['und'][0]['value']);
      $comment_body = str_replace("&nbsp;", " ",$comment_body);  
      foreach ($list as $data){
        $pos = stripos($comment_body, $data); 
        if ($pos !== false) {
          $swear_word[] = $data;
        }
      } 
      if(count($swear_word)){
        $swear_word = implode(", ", $swear_word);
        $params = array(
          '@path' => $comment_url, 
          '@words' => $swear_word, 
        );   
        foreach ($to as $email) {
          drupal_mail($module, $key, $email, $language, $params);
        }
      }
      break;
    }
  }
}
function swear_email_mail($key, &$message, $params) { 
  switch($key) {
   case 'swear':
    $message['subject'] = variable_get('swear_email_subject','Questionable language detected');
    $message['body'][] = variable_get('swear_email_body','There were usage of questionable language detected in the comment. To review please follow this URL,');
    $message['body'][] = t('The following swear word/s are used: @words ',$params);
    $message['body'][] = t('@path',$params);    
    break;
  }
}   



