<?php
// function node1_custom_init(){
	
// }

function node1_custom_menu() {
	$items['admin/nodechecktest'] = array(
		'title' => t('Link updates'),
		'page callback' => 'node1_custom_report_form',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	return $items;
}

function node1_custom_report_form() {		
	return drupal_get_form('node1_custom_create_form');
}

function node1_custom_create_form($form_state){

	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Consolidate12'),
		// '#ajax' => 	array(
		// 				'callback' => 'aah_gn_petition_report_distribute_submit',
		// 				'wrapper' => 'embedcode-div'
		// 			)
		'#submit' => array('aah_gn_petition_report_distribute_submit'),
	);
	
	return $form;	
}
//code
function aah_gn_petition_report_distribute_submit($form, &$form_state) {
	//dpm("I am here :) ");
	$contenttypes = array("article",
				"page",
				"basic_page_with_hero",
				"courses",
				"forum_discussion",
				"events",
				"job_vacancy",
				"my_voice_blog",
				);

	
	foreach ($contenttypes as $type) {
		//dpm($type);
    	$nodes = node_load_multiple(array(), array('type' => $type)); 
		foreach($nodes as $products)
		{
			// if($products->nid == 74571)
			// {
				$my_field_body = field_get_items('node', $products, 'body');
				$body = $my_field_body[0]['value'];
				$str = "http://ambitiousaboutautismwv3gzb6ax5.devcloud.acquia-sites.com";
				if (strpos($body, $str) !== false) 
				{
					$updatedvalue1 = str_replace($str,"", $body);
					dpm($updatedvalue1);
					$products->body[$products->language][0]['value'] = $updatedvalue1;      
					field_attach_update('node', $products);

					//sending the node id to database
					$record = array(
	    				"resultset" => $products->nid,
	    			);
	  				drupal_write_record('node_error_log1', $record);
				}
			//}
		}
	}

	$form['results']['#value'] = "Test";

	return $form['results'];
}

?>